polls/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.polls, name="Polls"),
    path("register", views.register, name="Register"),
    path("login", views.login, name="Login"),
    path("logout", views.logout, name="Logout"),
    path("add_poll", views.add_poll, name="Add Poll"),
    path("add_poll_process", views.add_poll_process, name="Add Poll Process"),
    path("my_poll", views.my_polls, name="My Polls"),
    path("search", views.search, name="Search"),
    path("vote/<int:poll_id>", views.vote, name="Vote"),
    path("result_map", views.result_map, name="Result map"),
    path("result/<int:poll_id>", views.result, name="Result"),
    path("profile/<int:user_id>", views.profile, name="Profile"),
    path("follow/<int:followed_id>/<int:follower_id>", views.follow, name="Follow"),
    path("unfollow/<int:followed_id>/<int:follower_id>", views.unfollow, name="Unfollow"),
    path("discover", views.discover, name="Discover"),


]

polls_app/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'polls.views.my_custom_page_not_found_view'
handler500 = 'polls.views.my_custom_error_view'
handler403 = 'polls.views.my_custom_permission_denied_view'
handler400 = 'polls.views.my_custom_bad_request_view'

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


# Question model

class Poll(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    date_published = models.DateTimeField()
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.text


# Choices model

class Choices(models.Model):
    question = models.ForeignKey(Poll, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    votes = models.IntegerField()

    def __str__(self):
        return self.text


class PollsUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    vote_count = models.IntegerField(default=0)
    question_count = models.IntegerField(default=0)
    follower_count = models.IntegerField(default=0)
    following_count = models.IntegerField(default=0)


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Question = models.ForeignKey(Poll, on_delete=models.CASCADE)
    Option = models.ForeignKey(Choices, on_delete=models.CASCADE)
    date = models.DateTimeField()


class Follow(models.Model):
    user = models.ForeignKey(User, related_name='user', on_delete=models.CASCADE)
    follow_user = models.ForeignKey(User, related_name='follow_user', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

polls/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    required_css_class = 'form-control'
    username = forms.CharField(label="username", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}))
    password = forms.CharField(label="password", max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'password'}))


class RegisterForm(forms.ModelForm):
    username = forms.CharField(label="username", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'username'}))
    password = forms.CharField(label="password", max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'password'}))
    email = forms.CharField(label="email", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'email'}))
    first_name = forms.CharField(label="firstname", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'firstname'}))
    last_name = forms.CharField(label="lastname", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control','placeholder': 'lastname'}))

    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']

polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import LoginForm, RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_process
from django.contrib.auth import logout as logout_process
from django.contrib.auth.decorators import login_required
from .models import PollsUser, Poll, Choices, Vote, Follow
from django.template import loader
from django.utils import timezone
import datetime


def reverse(mlist):
    leni = len(mlist)
    length = int(leni/2)
    for i in range(length):
        mlist[i], mlist[leni - (i + 1)] = mlist[leni - (i + 1)],  mlist[i]

    return mlist


def home(request):
    return render(request, 'home.html', {})


def register(request):

    context = {}

    if request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            if User.objects.filter(username=username).exists():
                context["error"] = "Username already exists"
                context["form"] = form

                return render(request, 'register.html', context)

            else:
                if User.objects.filter(email=email).exists():
                    context["error"] = "Email already exists"
                    context["form"] = form

                    return render(request, 'register.html', context)

                user = form.save(commit=False)
                user.set_password(user.password)
                user.save()

                u = User.objects.get(username=username)
                pu = PollsUser(user=u, vote_count=0, question_count=0, follower_count=0, following_count=0)
                pu.save()

                return redirect('Polls')
        else:
            context["error"] = "Username or email already exists"
            context["form"] = form

            return render(request, 'register.html', context)
    form = RegisterForm()
    context["form"] = form
    return render(request, 'register.html', context)


def login(request):
    context = {}

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            u = authenticate(request, username=username, password=password)

            if u is not None:
                login_process(request, u)
                return redirect(request.GET.get('next'))

            else:
                context["error"] = "Invalid Username or password"
                context["form"] = LoginForm(request.POST)

                return render(request, 'login.html', context)

    form = LoginForm()
    context["form"] = form
    return render(request, 'login.html', context)


def logout(request):
    logout_process(request)

    return redirect("Polls")


@login_required(login_url='/login')
def polls(request):
    polls_list = Poll.objects.all().order_by('date_published', 'votes')
    main_list = []
    sub_list = []
    for poll in polls_list:
        if Follow.objects.filter(user=request.user).filter(follow_user=poll.user).exists():
            if poll.date_published >= timezone.now() - datetime.timedelta(days=5):
                main_list.append(poll)
        else:
            sub_list.append(poll)

    context = {
        "main_polls": reverse(main_list),
        "sub_polls": reverse(sub_list),
    }

    if len(main_list) == 0:
        context["main_is_empty"] = True

    return render(request, 'polls.html', context)


@login_required(login_url='/login')
def add_poll(request):
    context = {
         "nums": [1, 2],
         "total": 2
    }
    if request.method == 'POST':
        num = int(request.POST["number_choices"])
        nums = []
        for i in range(num):
            nums.append(i+1)
        context["nums"] = nums
        context["total"] = len(nums)

        return render(request, 'add_poll.html', context)

    return render(request, 'add_poll.html', context)


def add_poll_process(request):
    user = request.user
    text = request.POST["text"]
    total = int(request.POST["number_of_choices"])

    q = Poll(user=user, text=text, date_published=timezone.now())
    q.save()
    pu = PollsUser.objects.get(user=user)
    pu.question_count += 1
    pu.save()

    for i in range(total):
        text = request.POST[f"{i+1}"]
        c = Choices(question=q, text=text, votes=0)
        c.save()

    return redirect('Polls')


@login_required(login_url='/login')
def my_polls(request):
    polls_list = Poll.objects.filter(user=request.user)
    context = {
        "polls": polls_list
    }
    if len(polls_list) == 0:
        context["empty"] = True

    if request.method == 'POST':
        p_id = request.POST['poll_id']
        p = Poll.objects.get(pk=p_id)
        p.delete()
        polls_list = Poll.objects.filter(user=request.user)
        context["polls"] = polls_list

        pu = PollsUser.objects.get(user=request.user)
        pu.question_count -= 1
        pu.save()

    return render(request, 'my_polls.html', context)


@login_required(login_url='/login')
def vote(request, poll_id):

    poll = Poll.objects.get(pk=poll_id)
    context = {
        "poll": poll
    }

    if Vote.objects.filter(user=request.user).filter(Question=poll).exists():
        context["already_voted"] = True

    if request.method == 'POST':
        option_id = request.POST["option"]
        choice = Choices.objects.get(pk=option_id)

        choice.votes += 1
        choice.save()

        v = Vote(user=request.user, Question=poll, Option=choice, date=timezone.now())
        v.save()

        poll.votes += 1
        poll.save()

        pu = PollsUser.objects.get(user=request.user)
        pu.vote_count += 1
        pu.save()

        return redirect('Result', poll.id)

    return render(request, 'vote.html', context)


@login_required(login_url='/login')
def result(request, poll_id):
    p = Poll.objects.get(pk=poll_id)
    context = {
        "poll": p
    }
    return render(request, 'result.html', context)


def profile(request, user_id):
    user = User.objects.get(pk=user_id)
    pu = PollsUser.objects.get(user=user)
    users_polls = Poll.objects.filter(user=user)

    context = {
        "user": user,
        "polluser": pu,
        "polls": users_polls
    }
    if len(users_polls) == 0:
        context["empty"] = True
    if user != request.user:
        context["other"] = True
        if Follow.objects.filter(user=request.user).filter(follow_user=user).exists():
            context["following"] = True

    return render(request, 'profile.html', context)


@login_required(login_url='/login')
def result_map(request):
    votes = Vote.objects.filter(user=request.user)

    questions = []
    for i in votes:
        questions.append(i.Question)

    context = {
        "questions": questions,
        "length": len(questions)
    }

    return render(request, 'result_map.html', context)


@login_required(login_url='/login')
def follow(request, followed_id, follower_id):
    followed = User.objects.get(pk=followed_id)
    follower = User.objects.get(pk=follower_id)

    f = Follow(user=follower, follow_user=followed, date=timezone.now())
    f.save()

    pu = PollsUser.objects.get(user=follower)
    pu.following_count += 1
    pu.save()

    pu = PollsUser.objects.get(user=followed)
    pu.follower_count += 1
    pu.save()

    return redirect('Profile', followed_id)


@login_required(login_url='/login')
def unfollow(request, followed_id, follower_id):

    follower = User.objects.get(pk=follower_id)
    followed = User.objects.get(pk=followed_id)
    f = Follow.objects.filter(user=follower).filter(follow_user=followed)
    f = f[0]
    f.delete()

    pu = PollsUser.objects.get(user=follower)
    pu.following_count -= 1
    pu.save()

    pu = PollsUser.objects.get(user=followed)
    pu.follower_count -= 1
    pu.save()

    return redirect('Profile', followed_id)


@login_required(login_url='/login')
def discover(request):
    pu = PollsUser.objects.exclude(user=request.user).order_by('question_count', 'vote_count', 'follower_count', 'following_count')

    context = {
        "poll_users": pu
    }
    return render(request, 'discover.html', context)


def search(request):

    search_text = request.GET["search"]
    s_polls = Poll.objects.filter(text__icontains=search_text)

    context = {
        "search_polls": s_polls
    }

    if len(s_polls) == 0:
        context["empty"] = True

    return render(request, 'search.html', context)


def my_custom_page_not_found_view(request, exception):
    context = {
        "error_num": "404"
    }

    return render(request, 'error.html', context)


def my_custom_error_view(request):
    context = {
        "error_num": "500"
    }

    return render(request, 'error.html', context)


def my_custom_permission_denied_view(request, exception):
    context = {
        "error_num": "403"
    }

    return render(request, 'error.html', context)


def my_custom_bad_request_view(request, exception):
    context = {
        "error_num": "400"
    }

    return render(request, 'error.html', context)

polls/templates/my_polls.html
{% extends 'base.html' %}
{% block title %}{{request.user}}'s Polls{% endblock title %}
{% block info %}This page is the page that shows all the polls posted by you {% endblock info%}
{% block content %}
{% if empty %}
     <div class="card card-nav-tabs text-center purple_bg">
  <div class="card-header card-header-primary">
    Hey there!
  </div>
  <div class="card-body">
    <p class="card-text">It seems there it seems you haven't made any polls yes, start now by clicking on the button below.</p>
    <a href="{% url 'Add Poll'%}" class="btn btn-default">Create Poll</a>
  </div>

</div>
{% else %}
{% for poll in polls %}

<div class="card" style="width: 20rem; float: left; margin:10px; ">
  <div class="card-body">
    <form method="post">
      {% csrf_token %}
      <input type="text" name="poll_id" style="display: none;" value = "{{ poll.id }}">
          <button class="btn btn-warning btn-fab btn-icon btn-round delete_poll" type="submit">
  <i class="tim-icons icon-simple-remove "></i>
</button>
    </form>

    <h4 class="card-title">Question {{poll.id }}</h4>

    <h6 class="card-subtitle mb-2 text-muted">{{ poll.date_published }}</h6>
    <p class="card-text">{{poll.text}}</p>
    <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    {% for choice in poll.choices_set.all %}
    <li class="list-group-item black_text">{{choice.text}}</li>
    {% endfor %}
  </ul>
</div>
    <h6 class="card-subtitle mb-2 text-muted">{{poll.user}}</h6>
    <a type="button" href="{% url 'Result' poll.id %}" class="btn btn-default">Result</a>

  </div>
</div>
{% endfor %}
{% endif %}
{% endblock content %}

polls/templates/polls.html
{% extends 'base.html' %}
{% block title %}Polls{% endblock title %}
{% block info %} This page renders all the polls and allows you to vote by clicking the vote button, if you have already voted that poll, it will take you straight to the results page{% endblock info %}
{% block content %}
<div class="card card-nav-tabs text-center">

  <div class="card-body">
    <h4 class="card-title">These are recent polls by pollsters you follow</h4>
  </div>

</div>
{% if main_is_empty %}
  <div class="card card-nav-tabs text-center purple_bg">
  <div class="card-header card-header-primary">
    Hey there!
  </div>
  <div class="card-body">
    <p class="card-text">It seems there are no new polls by the pollsters you follow, you can discover more pollsters by clicking on the button below.</p>
    <a href="{% url 'Discover'%}" class="btn btn-default">Discover pollsters</a>
  </div>

</div>
{% else %}
{% for poll in main_polls%}
<div class="card" style="width: 20rem; float: left; margin:10px; ">
  <div class="card-body" style="height:25rem;">
    <h4 class="card-title">Question {{poll.id }}</h4>
    <h6 class="card-subtitle mb-2 text-muted">{{ poll.date_published }}</h6>
    <p class="card-text">{{poll.text}}</p>
    <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    {% for choice in poll.choices_set.all %}
    <li class="list-group-item black_text">{{choice.text}}</li>
    {% endfor %}
  </ul>
</div>
    <a href="{% url 'Profile' poll.user.id %}"><h6 class="card-subtitle mb-2 text-muted to_lower">{{poll.user}}</h6></a>
    <a type="button" href="{% url 'Vote' poll.id %}" class="btn btn-success">Vote</a>
  </div>
</div>
{% endfor %}
{% endif %}

<br>
<br>

<div class="card card-nav-tabs text-center">

  <div class="card-body">
    <h4 class="card-title"> Here are other polls by our pollsters </h4>
  </div>

</div>


{% for poll in sub_polls %}
<div class="card" style="width: 20rem; float: left; margin:10px; ">
  <div class="card-body" style="height:25rem;">
    <h4 class="card-title">Question {{poll.id }}</h4>
    <h6 class="card-subtitle mb-2 text-muted">{{ poll.date_published }}</h6>
    <p class="card-text">{{poll.text}}</p>
    <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    {% for choice in poll.choices_set.all %}
    <li class="list-group-item black_text">{{choice.text}}</li>
    {% endfor %}
  </ul>
</div>
    <a href="{% url 'Profile' poll.user.id %}"><h6 class="card-subtitle mb-2 text-muted to_lower">{{poll.user}}</h6></a>
    <a type="button" href="{% url 'Vote' poll.id %}" class="btn btn-success">Vote</a>
  </div>
</div>
{% endfor %}
{% endblock content %}

polls/templates/profile.html
{% extends 'base.html' %}
{% block title%}Profile{% endblock title%}
{% block content %}
      <div class="row">
             <div class="col-md-4">
            <div class="card card-user">
              <div class="card-body">
                <p class="card-text">
                  <div class="author">
                    <div class="block block-one"></div>
                    <div class="block block-two"></div>
                    <div class="block block-three"></div>
                    <div class="block block-four"></div>
                    <a href="javascript:void(0)">
                      <h4 class="card-title">{{ user }}</h4>
                    </a>
                    <p class="description">
                       {{user.first_name}} {{user.last_name}}
                    </p>
                <br>

                     <div class="table-responsive">
                  <table class="table tablesorter " id="">
                    <thead class=" text-primary">
                      <tr>
                        <th>
                          polls
                        </th>
                        <th>
                          Votes
                        </th>
                        <th>
                          Followers
                        </th>
                        <th class="text-center">
                          Following
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>
                          {{ polluser.question_count}}
                        </td>
                        <td>
                          {{ polluser.vote_count}}
                        </td>
                        <td>
                          {{ polluser.follower_count}}
                        </td>
                        <td class="text-center">
                          {{ polluser.following_count}}
                        </td>
                      </tr>

                    </tbody>
                  </table>
                </div>

                {% if other %}
                {% if following %}
                    <a type="button"  href="{% url 'Unfollow' user.id request.user.id %}" class="btn btn-warning" style="color: white;">Unfollow</a>
                {% else %}
                    <a type="button"  href="{% url 'Follow' user.id request.user.id %}" class="btn btn-success" style="color: white;">Follow</a>
                {% endif %}

                {% endif %}
                  </div>
              </div>

            </div>
            </div>

            <div class="card col-md-7" style="float:right;">
              <div class="card-header">
                <h5 class="title">{{user}}'s Polls</h5>
              </div>
                {% if empty %}
                 {% if other %}
  <div class="card card-nav-tabs text-center purple_bg">
  <div class="card-header card-header-primary">
    Oops!!
  </div>
  <div class="card-body">
    <p class="card-text">It seems looks like {{user}} doesnt have any polls yet, but dont worry, soon enough they will.</p>
  </div>

</div>
                {% else %}
                <div class="card card-nav-tabs text-center purple_bg">
  <div class="card-header card-header-primary">
    Hey there!
  </div>
  <div class="card-body">
    <p class="card-text">It seems you dont have any polls yet, click on the button below to create polls.</p>
    <a href="{% url 'Add Poll' %}" class="btn btn-default">Create Polls</a>
  </div>

</div>
                {% endif %}
                {% else %}
              <div class="card-body">
                      {% for poll in polls %}
                  <h4 class="card-title">{{poll.text}}</h4>
                          <div class="row" id="myChart{{poll.id}}">

                                <div class="card-body col-md-4">
                <div class="table-responsive">
                  <table class="table tablesorter " id="vote_data">
                    <thead class=" text-primary">
                      <tr>
                        <th>
                          Option
                        </th>
                        <th class="text-center">
                            Votes
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for option in poll.choices_set.all%}
                      <tr>
                        <td class="option_name">
                          {{ option.text }}
                        </td>
                        <td class="text-center option_value">
                          {{ option.votes }}
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="card-body">
                <div class="chart-area">
                        <canvas id="Chart{{poll.id}}" style="float: right"></canvas>
                </div>
              </div>
              </div>
            {% if other %}
                    <a type="button"  href="{% url 'Vote' poll.id %}" class="btn btn-success" style="color: white;">Vote</a>
                {% endif %}
                <br>
                <br>
                <br>
                <br>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
    var current_chart = "myChart{{poll.id}}";
    var draw_chart = "Chart{{poll.id}}";
    var lis = document.getElementById(current_chart).getElementsByClassName("option_name");

    var num_lis = document.getElementById(current_chart).getElementsByClassName("option_value");
    var list = [];
    var num_list = []
    for (const li of lis) {
    list.push(li.textContent);
}

    for (const li of num_lis) {
    num_list.push(parseInt(li.textContent));
}

    var ctx = document.getElementById(draw_chart).getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'bar',

    // The data for our dataset
    data: {
        labels: list,
        datasets: [{
            label: 'choice data',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: num_list
        }]
    },

    // Configuration options go here
    options: {}
});
</script>

                      {% endfor %}
              </div>
                {% endif %}

            </div>


{% endblock content%}

polls/templates/result.html
{% extends 'base.html' %}
{% block title %}Result{% endblock title %}
{% block info %}This page displays result of a poll you voted{% endblock info %}
{% block content %}
<div class="card card-nav-tabs">
  <h4 class="card-header card-header-info">Question {{ poll.id }}</h4>
  <div class="card-body">
    <h4 class="card-title">{{ poll.text }}</h4>
  </div>
</div>
<div>
<div class="col-lg-4" style="float: left;">
            <div class="card card-chart">
              <div class="card-header">
                <h5 class="card-category">Total Votes </h5>
                <h3 class="card-title"><i class="tim-icons icon-chart-pie-36 text-info"></i>{{poll.votes}}</h3>
              </div>
                    <div class="card-body">
                <div class="table-responsive">
                  <table class="table tablesorter " id="vote_data">
                    <thead class=" text-primary">
                      <tr>
                        <th>
                          Option
                        </th>
                        <th class="text-center">
                            Votes
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for option in poll.choices_set.all%}
                      <tr>
                        <td class="option_name">
                          {{ option.text }}
                        </td>
                        <td class="text-center option_value">
                          {{ option.votes }}
                        </td>
                      </tr>
                     {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>

            </div>
          </div>

           <div class="col-lg-6" style="float: left;">
            <div class="card card-chart">
              <div class="card-header">
                <h5 class="card-category"> Bar Chart</h5>
                <h3 class="card-title"><i class="tim-icons icon-chart-bar-32 text-info"></i>{{ poll.text }}</h3>
              </div>
              <div class="card-body">
                <div class="chart-area">
                        <canvas id="myChart" style="float: right"></canvas>
                </div>
              </div>
            </div>
          </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
    var lis = document.getElementById("vote_data").getElementsByClassName("option_name");
    var num_lis = document.getElementById("vote_data").getElementsByClassName("option_value");
    var list = [];
    var num_list = []
    for (const li of lis) {
    list.push(li.textContent);
}
    for (const li of num_lis) {
    num_list.push(parseInt(li.textContent));
}
    console.log(lis)
    var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'bar',

    // The data for our dataset
    data: {
        labels: list,
        datasets: [{
            label: 'choice data',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: num_list
        }]
    },

    // Configuration options go here
    options: {}
});
</script>

{% endblock content %}

polls/templates/result_map.html
{% extends 'base.html' %}
{% block title%}Result Map{% endblock title%}
{% block info %}This page shows charts of all polls you have voted{% endblock info %}
{% block content %}
{% if length == 0 %}
     <div class="card card-nav-tabs text-center purple_bg">
  <div class="card-header card-header-primary">
    Hey there!
  </div>
  <div class="card-body">
    <p class="card-text">It seems you haven't voted any polls yet, you can start voting by clicking the button below.</p>
    <a href="{% url 'Polls'%}" class="btn btn-default">Vote Polls</a>
  </div>

</div>
{% else %}
    {% for question in questions %}

 <div id = "myChart{{question.id}}" style="display:none;">
    {% for choice in question.choices_set.all %}
        <div class="option_name">{{choice.text}}</div><div class="option_value">{{choice.votes}}</div>
     {% endfor %}
 </div>
         <div class="col-lg-10" style="float: left;">
            <div class="card card-chart">
              <div class="card-header">
                <h5 class="card-category"> Bar Chart</h5>
                <h3 class="card-title"><i class="tim-icons icon-chart-bar-32 text-info"></i>{{ question.text }}</h3>
              </div>
              <div class="card-body">
                <div class="chart-area">
                        <canvas id="Chart{{question.id}}" style="float: right"></canvas>
                </div>
              </div>
            </div>
          </div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
    var current_chart = "myChart{{question.id}}";
    var draw_chart = "Chart{{question.id}}";
    var lis = document.getElementById(current_chart).getElementsByClassName("option_name");

    var num_lis = document.getElementById(current_chart).getElementsByClassName("option_value");
    var list = [];
    var num_list = []
    for (const li of lis) {
    list.push(li.textContent);
}

    for (const li of num_lis) {
    num_list.push(parseInt(li.textContent));
}

    var ctx = document.getElementById(draw_chart).getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'line',

    // The data for our dataset
    data: {
        labels: list,
        datasets: [{
            label: 'choice data',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: num_list
        }]
    },

    // Configuration options go here
    options: {}
});
</script>

    {% endfor %}
{% endif %}
{% endblock content%}

polls/templates/search.html
{% extends 'base.html' %}
{% block title %}Search {{search}}{% endblock title %}
{% block info %}These are the search results for {{search}}{% endblock info %}
{% block content %}
{% if empty %}
 <div class="card card-nav-tabs text-center purple_bg">
  <div class="card-header card-header-primary">
    Oops!
  </div>
  <div class="card-body">
    <p class="card-text">It seems there are no polls that match your search request, try improving your search with less specific search requests.</p>
  </div>
</div>
{% else %}

{% for poll in search_polls %}
<div class="card" style="width: 20rem; float: left; margin:10px; ">
  <div class="card-body" style="height:25rem;">
    <h4 class="card-title">Question {{poll.id }}</h4>
    <h6 class="card-subtitle mb-2 text-muted">{{ poll.date_published }}</h6>
    <p class="card-text">{{poll.text}}</p>
    <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    {% for choice in poll.choices_set.all %}
    <li class="list-group-item black_text">{{choice.text}}</li>
    {% endfor %}
  </ul>
</div>
    <a href="{% url 'Profile' poll.user.id %}"><h6 class="card-subtitle mb-2 text-muted to_lower">{{poll.user}}</h6></a>
    <a type="button" href="{% url 'Vote' poll.id %}" class="btn btn-success">Vote</a>
  </div>
</div>
{% endfor %}
{% endif %}
{% endblock content %}